addClusterFacet
adobe/rum-distiller pull request #30
Opened 2024-12-02 09:12 UTC by asthabh23

## Description
This PR add `addCusterFacet` function and also add it's test coverage

## Related Issue
#21 

## How Has This Been Tested?
Tested on `cruncher.fixture.json` file which consists of real data

## Screenshots (if appropriate):
<img width="301" alt="Screenshot 2024-12-02 at 14 41 19" src="https://github.com/user-attachments/assets/4a441407-8815-4430-9a6c-b968f4dc3d7f">

For 92 URLs in the fixture, 1 cluster is created.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-12-03 13:18 UTC, trieloff requested changes
Left some comments for you.

2024-12-03 13:18 UTC, trieloff commented on distiller.js
> +        const clusters = urlProducer(facet.value);
`urlProducer` should be `producer` and an argument to the function.

2024-12-03 13:18 UTC, trieloff commented on distiller.js
> +  addClusterFacet(facetName, baseFacet, { count: clustercount = Math.floor(Math.log10(this.facets[baseFacet].length)) }) {
```suggestion
  addClusterFacet(facetName, baseFacet, { count: clustercount = Math.floor(Math.log10(this.facets[baseFacet].length)),
  producer: urlProducer }) {
```

2024-12-03 13:18 UTC, trieloff commented on distiller.js
> +      const totalUrlsInSupersetCluster = Math.floor(facetValues.length + clustercount);
```suggestion
      // Calculate the total number of items in the superset cluster
      const totalItemsInSupersetCluster = Math.floor(facetValues.length + clustercount);
```

Let's keep this generic here.

2024-12-03 13:18 UTC, trieloff commented on distiller.js
> +        return { facetMatch, ...clusters.filter(cluster => sortedClusters.includes(cluster)) };
```suggestion
        return [ facetMatch, ...clusters.filter(cluster => sortedClusters.includes(cluster)) ];
```

facet functions return arrays, not objects.

2024-12-03 13:50 UTC, asthabh23 commented on distiller.js
> +      }
updated in [62ee81f](https://github.com/adobe/rum-distiller/pull/30/commits/62ee81f1bb8749a2907d6b605159bd0cadb22a59)

2024-12-04 08:53 UTC, trieloff approved these changes
Almost there!

2024-12-04 08:53 UTC, trieloff commented on distiller.js
> +      }
```suggestion
      const [mostOccurringCluster] = [...clusterMap.entries()].sort((a, b) => b[1] - a[1]);
```

this should be more concise.

2024-12-04 09:14 UTC, merged