feat: normalise # in URLs for referrer classification
adobe/rum-distiller pull request #32
Opened 2024-12-05 13:48 UTC by asthabh23

## Description
This PR handles normalizing `#` in URLs for referrer classification 

## Related Issue
#31 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-12-05 14:05 UTC, langswei commented
Do we need to remove `/#` or just `#` to normalize?

2024-12-05 14:36 UTC, asthabh23 commented
> Do we need to remove `/#` or just `#` to normalize?

I wonder the same, I did `/#` initially.. but then i think `/` is still needed?

2024-12-05 14:40 UTC, langswei commented
My first thought is that consolidating `https://www.google.com` and `https://www.google.com/#` means we need to remove two chars: `/#`.  But I suppose this needs to be tested because I'm not sure if the redundancy in the facet was driven by UI vs. backend.

2024-12-05 14:45 UTC, asthabh23 commented
indeed, I also think that just removing the chars might not help.. removing duplicates will still be needed maybe separately., but I wanted to test that as next step once I get to test this change.
(since till the time it's not merged here, I cant test in explorer)

2024-12-06 11:11 UTC, trieloff requested changes
Let's also include a test case for that specific scenario

2024-12-06 11:11 UTC, trieloff commented on facets.js
> +      .filter((source) => source)
```suggestion
      .filter((source) => source)
      .map((source) => source.replace(/\/#$/, '')
```

that's how I'd do it.

2024-12-06 12:11 UTC, asthabh23 commented on facets.js
> +      .filter((source) => source)
updated.

2024-12-06 12:15 UTC, trieloff approved these changes

2024-12-06 12:17 UTC, merged